spring:
  profiles:
    active: dev,female
  datasource:
    url: jdbc:mysql://192.168.199.128:3306/dev
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: 123456
  redis:
    database: 0
    host: 192.168.56.101
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
    password: ''
    port: 6379
    timeout: 5000

server:
  port: 8083
  compression:
    enabled: true
logging:
  file:
    path: E:/java/demo/log





site:
  meta: this is a meta
  title: ${site.meta}
  keywords: this is a keywords
  settings:
    baseURL: http://www.baidu.coms

